c_compiler_version:       # [linux]
  - 9                     # [linux]
cxx_compiler_version:     # [linux]
  - 9                     # [linux]
fortran_compiler_version: # [linux]
  - 9                     # [linux]
cuda_compiler:
  - nvcc
